Add magento:fix-permissions command

diff --git a/mac b/mac
--- a/mac
+++ b/mac
@@ -43,6 +43,13 @@ RED='\033[1;31m'
 NC='\033[0m' # No Color
 
 #--------------------------------------------------------------------
+# Utilities
+#--------------------------------------------------------------------
+
+# Is the user running commands in sudo?
+IS_SUDO=$(sudo -n uptime 2>&1|grep "load"|wc -l)
+
+#--------------------------------------------------------------------
 # Functions
 #--------------------------------------------------------------------
 function get_branch_data()
@@ -1388,10 +1395,27 @@ elif [ "$function" == "magento:customer-create" ]; then
 
 elif [ "$function" == "magento:fix-permissions" ]; then
     if [ ! -f app/Mage.php ]; then
-        echo "Error: app/Mage.php file not found. Please make sure that you are currently on the root of the Magento project."
+        printf "${RED}Error: app/Mage.php file not found. Please make sure that you are currently on the root of the Magento project."
 	else
-	    # TODO: Add script to fix permissions
-		echo "WIP"
+	    # Ask for the administrator password upfront
+        sudo -v
+
+        # Keep-alive: update existing `sudo` time stamp until `.osx` has finished
+        while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &
+
+	    if [ ${IS_SUDO} -gt 0 ]; then
+            find . -type f \-exec chmod 644 {} \;
+            find . -type d \-exec chmod 755 {} \;
+            find ./var -type d \-exec chmod 777 {} \;
+            find ./var -type f \-exec chmod 666 {} \;
+            find ./media -type d \-exec chmod 777 {} \;
+            find ./media -type f \-exec chmod 666 {} \;
+            chmod 777 ./app/etc
+            chmod 644 ./app/etc/*.xml
+        else
+            printf "${RED}Error: This script should be run as root so that file ownership changes can be set correctly\n"
+        fi
+
 	fi
 
 # Create sample order in Magento
