Refactor and cleanup code. Remove old commands. Update readme.

diff --git a/mac-cli/tools/install b/mac-cli/tools/install
--- a/mac-cli/tools/install
+++ b/mac-cli/tools/install
@@ -11,9 +11,6 @@ NC='\033[0m' # No Color
 PACKAGE_DIRECTORY="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 suggest_current(){
     case "$1" in
-        "mysql.sock")
-            current=$(netstat -ln | awk '/mysql\.sock/ { print $9 }')
-        ;;
         "editor")
             current=$EDITOR
         ;;
@@ -23,7 +20,7 @@ suggest_current(){
     esac
     if [ -n $current ]; then
         echo $current | pbcopy
-        echo "${NC}Press ⌘ V to insert current (${current})"
+        echo "${NC}Press ⌘V to insert current (${current})"
     fi
 }
 
@@ -34,45 +31,6 @@ main() {
     echo "================================================${NC}\n"
 
     git clone https://github.com/guarinogabriel/mac-cli.git --depth 1 && cd mac-cli
-    
-    echo "${LIGHTGREEN}Please enter path to mysql on your local machine:"
-    echo "${NC}Press enter without any value to keep default: /Applications/MAMP/Library/bin/mysql"
-    suggest_current mysql
-    read mysql_path
-    if [ ! -z "$mysql_path" -a "$mysql_path" != " " ]; then
-        LC_CTYPE=C sed -i'' -e "s#/Applications/MAMP/Library/bin/mysql#${mysql_path}#g" "$PACKAGE_DIRECTORY/mac-cli/mac"
-    fi
-
-    echo "${LIGHTGREEN}Please enter your mysql user:"
-    echo "${NC}Press enter without any value to keep default: root"
-    read mysql_user
-    if [ ! -z "$mysql_user" -a "$mysql_user" != " " ]; then
-        LC_CTYPE=C sed -i'' -e "s#mysql_user=\"root\"#mysql_user=\"${mysql_user}\"#g" "$PACKAGE_DIRECTORY/mac-cli/mac"
-    fi
-
-    echo "${LIGHTGREEN}Please enter your mysql password:"
-    echo "${NC}Press enter without any value to keep default: root"
-    echo "${NC}Type none if no password is used"
-    read mysql_password
-    if [ ! -z "$mysql_password" -a "$mysql_password" != " " ]; then
-        LC_CTYPE=C sed -i'' -e "s#mysql_password=\"root\"#mysql_password=\"${mysql_password}\"#g" "$PACKAGE_DIRECTORY/mac-cli/mac"
-    fi
-
-    echo "${LIGHTGREEN}Please enter path to the mysql socket on your local machine:"
-    echo "${NC}Press enter without any value to keep default: /Applications/MAMP/tmp/mysql/mysql.sock"
-    suggest_current mysql.sock
-    read mysql_socket
-    if [ ! -z "$mysql_socket" -a "$mysql_socket" != " " ]; then
-        LC_CTYPE=C sed -i'' -e "s#/Applications/MAMP/tmp/mysql/mysql.sock#${mysql_socket}#g" "$PACKAGE_DIRECTORY/mac-cli/mac"
-    fi
-
-    echo "${LIGHTGREEN}Please enter path to mysqldump on your local machine:"
-    echo "${NC}Press enter without any value to keep default: /Applications/MAMP/Library/bin/mysqldump"
-    suggest_current mysqldump
-    read mysql_dump
-    if [ ! -z "$mysql_dump" -a "$mysql_dump" != " " ]; then
-        LC_CTYPE=C sed -i'' -e "s#/Applications/MAMP/Library/bin/mysqldump#${mysql_dump}#g" "$PACKAGE_DIRECTORY/mac-cli/mac"
-    fi
 
     echo "${LIGHTGREEN}Please enter path to your Dropbox folder:"
     echo "${NC}Press enter without any value to keep default: /Users/$(id -u -n)/Dropbox/"
@@ -102,21 +60,21 @@ main() {
 
     if [ ! -d /usr/local/bin ]; then
             echo "bin not found"
-    	{
-    		echo "creating bin directory..."
-    		mkdir -p /usr/local/bin
-    	} || {
-    		echo "error in creating bin directory"
-    		exit 1
-    	}
+      {
+        echo "creating bin directory..."
+        mkdir -p /usr/local/bin
+      } || {
+        echo "error in creating bin directory"
+        exit 1
+      }
     fi
 
     cp "$PACKAGE_DIRECTORY/mac-cli/mac" /usr/local/bin/mac
-	cp -r "$PACKAGE_DIRECTORY/mac-cli/mac-cli/" /usr/local/bin/mac-cli
-	chmod -R +x /usr/local/bin/mac-cli/*
+    cp -r "$PACKAGE_DIRECTORY/mac-cli/mac-cli/" /usr/local/bin/mac-cli
+    chmod -R +x /usr/local/bin/mac-cli/*
 
     if [ ! -f /usr/local/bin/brew ]; then
-        echo "Installing homebrew..."
+        echo "Installing Homebrew..."
         echo "${GREEN}/usr/bin/ruby -e '\$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)'\n${NC}"
         /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
     fi
@@ -125,199 +83,19 @@ main() {
         echo "Installing Git..."
         echo "${GREEN}brew install git\n${NC}"
         brew install git
-	fi
+	  fi
 
     if [ ! -f /usr/local/bin/pv ]; then
         echo "Installing pv (Pipe Viewer)..."
         echo "${GREEN}brew install pv\n${NC}"
         brew install pv
-	fi
-
-    if ! which node > /dev/null; then
-        echo "Installing node..."
-        echo "${GREEN}brew install node\n${NC}"
-        brew install node
-	fi
-
-    if [ ! -f /usr/local/bin/python ]; then
-        echo "Installing Python..."
-        echo "${GREEN}brew install python\n${NC}"
-        brew install python
-	fi
-
-    if [ ! -f /usr/local/bin/fdupes ]; then
-        echo "Installing fdupes..."
-        echo "${GREEN}brew install fdupes\n\n${NC}"
-        brew install fdupes
-    fi
+	  fi
 
     if [ ! -f /usr/local/bin/wget ]; then
         echo "Installing wget..."
         printf "${GREEN}brew install wget\n${NC}"
         brew install wget
-	fi
-
-    if [ ! -f /usr/local/bin/composer.phar ] && [ ! -f /usr/local/bin/composer ]; then
-        printf "${LIGHTGREEN}"
-        read -r -p "Would you like to install composer (https://getcomposer.org/)? (Yes / No)" response
-        case $response in
-            [yY][eE][sS]|[yY])
-                echo "Installing composer..."
-                echo "${GREEN}brew install composer\n${NC}"
-                brew install composer
-                ;;
-            *)
-                ;;
-        esac
-        printf "${NC}"
-    fi
-
-    if [ ! -f /usr/local/bin/compass ]; then
-        printf "${LIGHTGREEN}"
-        read -r -p "Would you like to install Compass (http://compass-style.org/)? (Yes / No)" response
-        case $response in
-          [yY][eE][sS]|[yY])
-            echo "Installing Compass..."
-            echo "${GREEN}sudo gem install -n /usr/local/bin compass\n${NC}"
-            sudo gem install -n /usr/local/bin compass
-          ;;
-          *)
-          ;;
-        esac
-        printf "${NC}"
-    fi
-
-    if [ ! -f /usr/local/bin/sass ]; then
-        printf "${LIGHTGREEN}"
-        read -r -p "Would you like to install SASS (http://sass-lang.com/)? (Yes / No)" response
-        case $response in
-          [yY][eE][sS]|[yY])
-            echo "Installing SCSS..."
-            echo "${GREEN}gem install sass\n${NC}"
-            gem install sass
-          ;;
-          *)
-          ;;
-        esac
-        printf "${NC}"
-    fi
-
-    if [ ! -f /usr/local/bin/mycli ]; then
-        printf "${LIGHTGREEN}"
-        read -r -p "Would you like to install MySQL CLI to manage your databases (https://github.com/dbcli/mycli)? (Yes / No)" response
-        case $response in
-            [yY][eE][sS]|[yY])
-                echo "Installing mycli (MySQL CLI - https://github.com/dbcli/mycli)..."
-                echo "${GREEN}brew install mycli\n${NC}"
-                brew install mycli
-                ;;
-            *)
-                ;;
-        esac
-        printf "${NC}"
-	fi
-
-    if [ ! -f /usr/local/bin/glances ]; then
-        printf "${LIGHTGREEN}"
-        read -r -p "Would you like to install Glances to access advanced information about the system (https://github.com/nicolargo/glances)? (Yes / No)" response
-        case $response in
-            [yY][eE][sS]|[yY])
-                echo "Installing Glances (https://github.com/nicolargo/glances)..."
-                echo "${GREEN}pip install glances\n${NC}"
-                pip install glances
-                ;;
-            *)
-                ;;
-        esac
-        printf "${NC}"
-	fi
-
-    if [ ! -f /usr/local/bin/speedtest-cli ]; then
-        printf "${LIGHTGREEN}"
-        read -r -p "Would you like to install Fast CLI to run internet speed tests from your command line (https://github.com/sindresorhus/fast-cli)? (Yes / No)" response
-        case $response in
-            [yY][eE][sS]|[yY])
-                echo "Installing Fast CLI (https://github.com/sindresorhus/fast-cli)..."
-                echo "${GREEN}npm install --global fast-cli\n${NC}"
-                npm install --global fast-cli
-                ;;
-            *)
-                ;;
-        esac
-        printf "${NC}"
-	fi
-
-    if [ ! -f /usr/local/bin/n98-magerun.phar ]; then
-        printf "${LIGHTGREEN}"
-        read -r -p "Would you like to install N98 Magerun to access to Magento 1 command line tools (https://github.com/netz98/n98-magerun)? (Yes / No)" response
-        case $response in
-            [yY][eE][sS]|[yY])
-                echo "Installing N98 Magerun (https://github.com/netz98/n98-magerun)..."
-                echo "${GREEN}wget https://files.magerun.net/n98-magerun.phar\n${NC}"
-                wget https://files.magerun.net/n98-magerun.phar
-                echo "${GREEN}chmod +x ./n98-magerun.phar\n${NC}"
-                chmod +x ./n98-magerun.phar
-                echo "${GREEN}sudo mv ./n98-magerun.phar /usr/local/bin/\n${NC}"
-                sudo mv ./n98-magerun.phar /usr/local/bin/
-                ;;
-            *)
-                ;;
-        esac
-        printf "${NC}"
-	fi
-
-    if [ ! -f /usr/local/bin/n98-magerun2.phar ]; then
-        printf "${LIGHTGREEN}"
-        read -r -p "Would you like to install N98 Magerun 2 to access to Magento 2 command line tools (https://github.com/netz98/n98-magerun2)? (Yes / No)" response
-        case $response in
-            [yY][eE][sS]|[yY])
-                echo "Installing N98 Magerun 2 (https://github.com/netz98/n98-magerun2)..."
-                echo "${GREEN}wget https://files.magerun.net/n98-magerun2.phar\n${NC}"
-                wget https://files.magerun.net/n98-magerun2.phar
-                echo "${GREEN}chmod +x ./n98-magerun2.phar\n${NC}"
-                chmod +x ./n98-magerun2.phar
-                echo "${GREEN}sudo mv ./n98-magerun2.phar /usr/local/bin/\n${NC}"
-                sudo mv ./n98-magerun2.phar /usr/local/bin/
-                ;;
-            *)
-                ;;
-        esac
-        printf "${NC}"
-	fi
-
-    if [ ! -f /usr/local/bin/imageOptim ]; then
-        printf "${LIGHTGREEN}"
-        read -r -p "Would you like to install ImageOptim to optimize images from the command line? (Yes / No)" response
-        case $response in
-            [yY][eE][sS]|[yY])
-                echo "Installing ImageOptim..."
-                echo "${GREEN}brew cask install --appdir="~/Applications" imageoptim --force\n${NC}"
-                brew cask install --appdir="~/Applications" imageoptim --force
-
-                echo "Installing ImageOptim-CLI (https://github.com/JamieMason/ImageOptim-CLI)..."
-                echo "${GREEN}npm install -g imageoptim-cli\n${NC}"
-                npm install -g imageoptim-cli
-                ;;
-            *)
-                ;;
-        esac
-        printf "${NC}"
-	fi
-
-    if [ ! -f /usr/local/bin/istats ]; then
-        printf "${LIGHTGREEN}"
-        read -r -p "Would you like to install iStats access information about your Mac temperature and fan speed? (Yes / No)" response
-        case $response in
-            [yY][eE][sS]|[yY])
-                echo "Installing iStats..."
-                echo "${GREEN}sudo gem install iStats -n/usr/local/bin\n\n${NC}"
-                sudo gem install iStats -n/usr/local/bin
-                ;;
-            *)
-                ;;
-        esac
-        printf "${NC}"
-    fi
+	  fi
 
     if ! brew list | grep -q bash-completion ; then
 
